# Fetching the latest node image on alpine linux
FROM node:16-alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /usr/react-app

# Installing dependencies
COPY ./package.json /usr/react-app
RUN npm install --force

# Copying all the files in our project
COPY . .

# Starting our application
CMD npm start

EXPOSE 3354